### ISSUE TITLE
support for Sanguophages

### ISSUE THREAD

**Issue by LionelColaso** [AmCh-Q/RimWorldMod_NeedBarOverflow#3]
can you add support for Sanguophage currently u cannot make them take hemogen if food is 100%

**Comment by AmCh-Q** [comment]
If you only mean Sanguaophages cannot take hemogen when food is overflowing: That is a bug and I will try to get it fixed soon.  

If you also meant to suggest allowing hemogen to overflow:
Within the game's code, the Hemogen resource of Sanguophages is not built with Vanilla RW's need system. Instead, it is built with Biotech DLC's genetic resource system.  
That unfortunately means that (1) it is technically not a need bar, and (2) supporting it means working with a completely different system which I have no idea how and how long would it take.  
I will consider supporting that in the future, but that will not be my priority.

**Comment by LionelColaso** [comment]
> If you only mean Sanguaophages cannot take hemogen when food is overflowing: That is a bug and I will try to get it fixed soon.

My only concern is as u mentioned when food is overflowing i can't make them take hemogen even from inventory
also i am using this mod which does not let the food bar decrease 
the issue happens regardless of the below mod
https://steamcommunity.com/sharedfiles/filedetails/?id=3013615960

**Comment by AmCh-Q** [comment]
Should be fixed now with https://github.com/AmCh-Q/RimWorldMod_NeedBarOverflow/releases/tag/v1.2.5
That version won't be on Steam just yet, need some time to test if it works well.

**Comment by LionelColaso** [comment]
i found the actual reason for the issue it was this mod that was interfearring which baically depends on Alpha Genes mod

https://steamcommunity.com/sharedfiles/filedetails/?id=3013615960

this is the patch in the mod

<Patch>

				<Operation Class="PatchOperationAdd">
					<xpath>Defs/GeneDef[defName="Hemogenic"]</xpath>
					<value>
						<modExtensions>
							<li Class="VanillaGenesExpanded.GeneExtension">
								<hediffToWholeBody>AG_NoFood</hediffToWholeBody>
							</li>
						</modExtensions>
						<disablesNeeds>
						<li>Rest</li>
						</disablesNeeds>
					</value>
				</Operation>

				<Operation Class="PatchOperationReplace">
				<xpath>Defs/GeneDef[defName="Hemogenic"]/description</xpath>
					<value>
						<description>Carriers of this gene have a reserve of biological strength powered by a resource called hemogen. The resource can be gained and spent in various ways, all of which are unlocked by other genes.\n\nCarriers lose 2 hemogen per day from biological entropy, they do not require food, water, or sleep.</description>
					</value>
			</Operation>
</Patch>

**Comment by AmCh-Q** [comment]
I was able to reproduce that the pawns couldn't take Hemogen when they are full, even without that mod.
Anyways thank you for your help! I think it's fixed now, so I will close this issue now unless you have more to add.
