### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by Crusader2010** [AmCh-Q/RimWorldMod_NeedBarOverflow#4]
Hello,

I've been having a strange issue with the Sleep and Recreation bars. They seem to never go below 200%, even though my pawns still sleep and still do recreation-related stuff.

The issue is even more obvious during caravan travel since it seems to be able to travel indefinitely (without sleep).

Any idea what could be at fault here? I'm using ~500 mods, so likely can't debug properly. There's no red error either.

I have set the bars' setup in the options to 200% maximum, "lose level faster" at 50%, and "gain level slower" unchecked.

Thanks!

**Comment by AmCh-Q** [comment]
Would you mind checking [version 1.2.6 under releases](https://github.com/AmCh-Q/RimWorldMod_NeedBarOverflow/releases/tag/v1.2.6)? This version has not been updated on Steam yet but I've tried fixing that.

**Comment by Crusader2010** [comment]
Thank you, it seems to be working nicely!
